---
title: "Movie recommendations"
author:
  - Rpita623:
      correspondence: "yes"
      email: janedoe@fosg.org
      orcid: 0000-0003-1689-0557
      institute:
        - github
institute:
  - fosg:
      name: Formatting Open Science Group
      address: 23 Science Street, Eureka, Mississippi, USA
  - fop: Federation of Planets
date: 10-10-2023
date-format: long
format: 
  docx:
    reference-doc: "../templates/template.docx" # Insert path for the DOCX file
execute:
  echo: true
  warning: false
  message: false
  comment: "#>"
  fig-path: "../figures/"
  fig-dpi: 600
filters:
  - ../templates/scholarly-metadata.lua
  - ../templates/author-info-blocks.lua
  - ../templates/pagebreak.lua
bibliography: references.bib
csl: "../templates/journal-of-archaeological-science.csl" # Insert path for the bib-style
keywords: |
  Movies; ratings
---

<!-- load environmental variables and libraries from external R scripts -->

```{r, include=FALSE}
install.packages(("here"), repos = "http://cran.us.r-project.org")
library(here)
sys.source(here("01-collect-data-Movie_Recommendation_System.R"), envir = knitr::knit_global())
sys.source(here("02-process-data-Movie_Recommendation_System.R"), envir = knitr::knit_global())
sys.source(here("03-visualize-data-Movie_Recommendation_System.R"), envir = knitr::knit_global())
```

Keywords: `r rmarkdown::metadata$keywords`

<!-- The actual document text starts here: -->

# Introduction

summary of movies

# Results

```{r, echo=FALSE}

#| label: qplot
#| cache: false

qplot(average_ratings, fill=I("steelblue"), col=I("red"), binwidth=0.1) +

ggtitle("Distribution of the average rating per user")
```

# Discussion

# Conclusion

\newpage

### Colophon

This report was generated on `r Sys.time()` using the following computational environment and dependencies:

```{r}
#| label: colophon
#| cache: false

# which R packages and versions?
if ("devtools" %in% installed.packages()) devtools::session_info()
```

The current Git commit details are:

```{r}
# what commit is this file at? 
if ("git2r" %in% installed.packages() & git2r::in_repository(path = ".")) git2r::repository(here::here())  
```
